steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/eng-metrics-app:$SHORT_SHA", '.']
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/eng-metrics-app:$SHORT_SHA"]
