steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/eng-metrics-app:$SHORT_SHA", '.']
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/eng-metrics-app:$SHORT_SHA"]
  - name: gcr.io/cloud-builders/kubectl
    args: ["set", "image", "deployment/eng-metrics-app", "eng-metrics-app=gcr.io/$PROJECT_ID/eng-metrics-app:$SHORT_SHA"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=eng-metrics-cluster"
